spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        payment-out:
          destination: payment
          content-type: application/json
stubrunner:
  cloud:
    eureka:
      enabled: false